name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make
      # exclude generated code from diff because `make` will generate with different whitespaces
      - run: git diff --exit-code -- ':(exclude)examples/web/src/gen/example/*'
