name: TypeScript
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.27.2
        with:
          node-version: 20
      - run: |
          npm ci
          npm run buf
          npm run lint
        working-directory: examples/web
      - run: git diff --exit-code
